### Site Settings ###
title               : Will Thomson
description         : >-
                      Paper scruncher, monitor puncher
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : anenglishgoat/anenglishgoat.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md



### Author Info ###
author:
  name              : Will Thomson
  image             : pages_img.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : willthomson1991@gmail.com
#  facebook          : your_username
  github            : anenglishgoat
# gitlab            : your_username
# instagram         : your_username
#  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : anenglishgoat
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name



### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"



### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
